# Generated by Django 4.2.4 on 2023-08-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_alter_house_options_alter_score_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
